/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import io.reactivex.rxjava3.core.Flowable;
import io.reactivex.rxjava3.schedulers.Schedulers;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Eslam Alaa
 */
public class MainApp extends javax.swing.JFrame {

    /**
     * Creates new form MainApp
     */
    public MainApp() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold default state="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        javax.swing.JButton get_from_api = new javax.swing.JButton();
        javax.swing.JButton save_to_database = new javax.swing.JButton();
        javax.swing.JButton get_from_database = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jPanel1.setBackground(new java.awt.Color(19, 58, 83));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(11, 33, 47));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        get_from_api.setText("API");
        get_from_api.addActionListener(this::get_from_apiActionPerformed);

        save_to_database.setText("save");
        save_to_database.addActionListener(this::save_to_databaseActionPerformed);

        get_from_database.setText("database");
        get_from_database.addActionListener(this::get_from_databaseActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(get_from_database, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(save_to_database, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(get_from_api, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(get_from_api)
                .addGap(44, 44, 44)
                .addComponent(save_to_database)
                .addGap(39, 39, 39)
                .addComponent(get_from_database)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void get_from_apiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_from_apiActionPerformed
        long start = System.nanoTime();
        ArrayList<String> urls = new ArrayList<>();
        urls.add("http://newsapi.org/v2/everything?q=bitcoin&sortBy=publishedAt&apiKey=de0418c6a6c54dde85c9e12b9a7bdf1e");
        urls.add("http://newsapi.org/v2/top-headlines?country=us&category=business&apiKey=de0418c6a6c54dde85c9e12b9a7bdf1e");
        urls.add("http://newsapi.org/v2/top-headlines?sources=techcrunch&apiKey=de0418c6a6c54dde85c9e12b9a7bdf1e");
        jTextArea1.setText("");
        Flowable.fromIterable(urls)
                .parallel()
                .concatMap(url-> Flowable.just(url)
                        .subscribeOn(Schedulers.newThread())
                        .map(w -> new api_manger(new URL(w)))
                        .map(w->w.display_json()+ "**********************************************\n"))
                .sequential()
                .subscribe(w->jTextArea1.setText(jTextArea1.getText() + w));
        long end = System.nanoTime();
        System.out.println("Time : " + ( (double) (end - start) /  1000000000.0   ));
    }//GEN-LAST:event_get_from_apiActionPerformed

    private void save_to_databaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_to_databaseActionPerformed

        ArrayList<String> urls = new ArrayList<>();
        data_manger dm = new data_manger();
        urls.add("http://newsapi.org/v2/everything?q=bitcoin&sortBy=publishedAt&apiKey=de0418c6a6c54dde85c9e12b9a7bdf1e");
        urls.add("http://newsapi.org/v2/top-headlines?country=us&category=business&apiKey=de0418c6a6c54dde85c9e12b9a7bdf1e");
        urls.add("http://newsapi.org/v2/top-headlines?sources=techcrunch&apiKey=de0418c6a6c54dde85c9e12b9a7bdf1e");


        Flowable.fromIterable(urls)
                .parallel()
                .concatMap(url-> Flowable.just(url)
                        .subscribeOn(Schedulers.newThread())
                        .map(w -> new api_manger(new URL(w)).json_to_object())
                        .map(article->Flowable.fromIterable(article)
                            .subscribe(w->dm.add_data(w.title,w.content)))

                )
                .sequential()
                .subscribe(w->System.out.println("done"));
    }//GEN-LAST:event_save_to_databaseActionPerformed

    private ArrayList<String > convert_rs_tostring(ResultSet rs){
        ArrayList<String > result =new ArrayList<>();
        while (true){
            try {
                if (!rs.next()) break;

                result.add(rs.getString("title") + "\n\n" + rs.getString("content") + "\n----------------------------------------------\n");
            } catch (SQLException throwable) {
                throwable.printStackTrace();
            }
        }
    return result;
    }

    private void get_from_databaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_from_databaseActionPerformed
        try {
            jTextArea1.setText("");
            final String[] result = {""};
            data_manger dm = new data_manger();
            ResultSet rs = dm.display();

            Flowable.fromArray(convert_rs_tostring(rs))
                    .parallel()
                    .concatMap(x->Flowable.just(x)
                            .subscribeOn(Schedulers.newThread())
                            .map(w-> result[0] = result[0] + w)

                    )
                    .sequential()
                    .subscribe(w->jTextArea1.setText(result[0]));
            System.out.println("data retrieved from database");
//            Flowable.fromArray(rs)
//                    .parallel()
//                    .runOn(Schedulers.io())
//                    .map(w->w.getString("title") + "\n\n" + w.getString("content") + "\n----------------------------------------------\n")
//                    .doOnNext(new Consumer<String>() {
//                        @Override
//                        public void accept(String s) throws Throwable {
//                            while (rs.next()){
//                                result[0]+=rs.getString("title") + "\n\n" + rs.getString("content") + "\n----------------------------------------------\n";
//
//                            }
//                            System.out.println("data retrieved from database ");
//                        }
//                    })
//                    .sequential()
//                    .subscribe(w->jTextArea1.setText( result[0]));
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(MainApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_get_from_databaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold default state="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainApp().setVisible(true));
    }

    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
